spring: 
  datasource:
    username: calCalc
    password: calCalc
    url: jdbc:mysql://localhost:3306/tallyCalCarbsDaily
    


logging:
  level:
    root: warn
    '[com.stewartlavenia]': debug
    
